# Generated by Django 2.2.1 on 2020-05-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPC_Level_pj_pd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_id', models.CharField(max_length=32, verbose_name='问题级别ID')),
                ('pl_name', models.CharField(max_length=128, verbose_name='问题级别名称')),
                ('pl_describe', models.CharField(max_length=255, verbose_name='问题级别描述')),
                ('pl_color', models.CharField(max_length=2, verbose_name='问题色别')),
                ('project_id', models.CharField(max_length=32, verbose_name='项目ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '问题级别',
                'verbose_name_plural': '问题级别信息',
                'db_table': 'MPC_Level_pj_pd',
                'ordering': ['pl_id'],
            },
        ),
        migrations.CreateModel(
            name='MPC_Project_pd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32, unique=True, verbose_name='项目ID')),
                ('project_creator_id', models.CharField(max_length=32, verbose_name='负责人')),
                ('project_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('project_code', models.CharField(max_length=32, verbose_name='邀请码')),
                ('project_td', models.CharField(max_length=255, verbose_name='项目说明')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目基础信息',
                'db_table': 'MPC_Project_pd',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='MPC_Schedule_pd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32, verbose_name='项目ID')),
                ('schedule_id', models.CharField(max_length=12, verbose_name='日程阶段')),
                ('schedule_name', models.CharField(max_length=64, verbose_name='阶段名称')),
                ('start_time', models.CharField(max_length=12, verbose_name='阶段开始时间')),
                ('end_time', models.CharField(max_length=12, verbose_name='阶段结束时间')),
                ('schedule_td', models.CharField(max_length=255, verbose_name='阶段事项')),
                ('schedule_speed', models.CharField(default=0, max_length=12, verbose_name='阶段完成度')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目日程',
                'verbose_name_plural': '项目日程信息',
                'db_table': 'MPC_Schedule_pd',
                'ordering': ['project_id'],
            },
        ),
    ]
