# Generated by Django 2.2.1 on 2020-05-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPC_Problem_complete_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_id', models.CharField(max_length=32, unique=True, verbose_name='问题ID')),
                ('ppc_describe', models.CharField(max_length=255, verbose_name='回复')),
                ('ppc_user_id', models.CharField(max_length=32, verbose_name='完成者')),
                ('ppc_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '问题进度',
                'verbose_name_plural': '项目问题进度信息',
                'db_table': 'MPC_Problem_complete_sch',
                'ordering': ['pp_id'],
            },
        ),
        migrations.CreateModel(
            name='MPC_problem_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_id', models.CharField(max_length=32, verbose_name='问题ID')),
                ('pp_title', models.CharField(max_length=32, verbose_name='标题')),
                ('pp_author', models.CharField(max_length=32, verbose_name='作者')),
                ('pp_information', models.CharField(max_length=255, verbose_name='问题详情')),
                ('pp_state', models.CharField(default='进行中', max_length=25, verbose_name='问题状态')),
                ('pp_time', models.CharField(default='0', max_length=20, verbose_name='预计用时')),
                ('pp_to_user', models.CharField(max_length=32, verbose_name='处理者')),
                ('project_id', models.CharField(max_length=32, verbose_name='项目ID')),
                ('pl_id', models.CharField(max_length=32, verbose_name='问题级别ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目问题',
                'verbose_name_plural': '项目问题信息',
                'db_table': 'MPC_problem_sch',
                'ordering': ['pp_id'],
            },
        ),
    ]
