# Generated by Django 2.2.1 on 2020-05-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPC_Category_pg_pmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_category_id', models.CharField(max_length=32, verbose_name='项目组成员分类ID')),
                ('pg_category_name', models.CharField(max_length=32, verbose_name='项目组名')),
                ('pg_category_describe', models.CharField(max_length=128, verbose_name='描述')),
                ('pg_id', models.CharField(max_length=32, verbose_name='项目组ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目组成员分类',
                'verbose_name_plural': '项目组成员分类信息',
                'db_table': 'MPC_Category_pg_pmd',
                'ordering': ['pg_category_id'],
            },
        ),
        migrations.CreateModel(
            name='MPC_Member_pg_pmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_id', models.CharField(max_length=32, verbose_name='项目组ID')),
                ('pg_uc_id', models.CharField(max_length=32, verbose_name='项目组成员分类ID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目组成员',
                'verbose_name_plural': '项目组成员信息',
                'db_table': 'MPC_Member_pg_pmd',
                'ordering': ['pg_id'],
            },
        ),
        migrations.CreateModel(
            name='MPC_Project_group_pmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_id', models.CharField(max_length=32, unique=True, verbose_name='项目组ID')),
                ('pg_name', models.CharField(max_length=128, verbose_name='项目组名')),
                ('project_id', models.CharField(max_length=32, verbose_name='项目ID')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目组',
                'verbose_name_plural': '项目组信息',
                'db_table': 'MPC_Project_group_pmd',
                'ordering': ['pg_id'],
            },
        ),
    ]
