# Generated by Django 2.2.1 on 2020-05-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPC_User_state_ud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='用户ID')),
                ('project_id', models.CharField(max_length=32, unique=True, verbose_name='当前项目ID')),
                ('pg_uc_id', models.CharField(max_length=32, verbose_name='用户等级')),
            ],
            options={
                'verbose_name': '用户状态记录',
                'verbose_name_plural': '用户状态信息',
                'db_table': 'MPC_User_state_ud',
            },
        ),
        migrations.CreateModel(
            name='MPC_User_ud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='用户ID')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('user_profile', models.CharField(default='', max_length=32, verbose_name='个人签名')),
                ('user_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('user_company', models.CharField(max_length=128, verbose_name='单位')),
                ('user_position', models.CharField(max_length=32, verbose_name='职位')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户基础信息',
                'db_table': 'MPC_User_ud',
                'ordering': ['c_time'],
            },
        ),
    ]
